### ISSUE TITLE
v2 helper function is __main__.py should move to hyp3-lib

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-rtc-gamma#98]

**Comment by jhkennedy** [comment]
This was done in #171, the release of [v2.3.2](https://github.com/ASFHyP3/hyp3-rtc-gamma/compare/v2.3.1...v2.3.2), with the upgrade to [hyp3lib v1.6.0](https://github.com/ASFHyP3/hyp3-lib/blob/develop/CHANGELOG.md#160)
