### ISSUE TITLE
upload_folder_to_s3() improvements

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-rtc-gamma#99]
should log each file being uploaded

shouldn't include the folder being uploaded in the s3 path

**Comment by jhkennedy** [comment]
Fixed in ASFHyP3/hyp3lib#212 and released in [hyp3lib v1.6.0](https://github.com/ASFHyP3/hyp3-lib/blob/develop/CHANGELOG.md#160)
